### ISSUE TITLE
It's possible import data ?

### ISSUE THREAD

**Issue by ricardojlrufino** [ppannuto/python-saleae#15]
You can import data using the API?
Such as importing a CSV?

**Comment by Marcus10110** [comment]
The Saleae software has no import features - only export features, intended for post-processing captured data with other tools or scripts.
If you're looking for wave form viewing software, the old classic is GTK wave. However I think there are a lot of other options too. I would guess that Sigrok's PulseView might import.

**Comment by ricardojlrufino** [comment]
I use Pulse View.

The point is that I think the Saleae software is better

Thanks
