### ISSUE TITLE
Doc for set_triggers_for_all_channels should specify digital channels

### ISSUE THREAD

**Issue by aschulm** [ppannuto/python-saleae#2]
The documentation for set_triggers_for_all_channels should specify "digital" channels for each of the mentions of channels. For example if you have the following channel config:

analog_channels = [0,1,2,3,4,5,6]
digital_channels = [7]

Then you should only pass _one_ trigger parameter into set_triggers_for_all_channels, just for the ditgital channel, even though there are a total of 8 active channels. Ideally this function would call get_active_channels and return a helpful error that says you only need to pass triggers for X digital channels.

**Comment by ppannuto** [comment]
I agree that checking the active channels would be best -- several of these functions are written but untested. I copied the whole API when I made the library, but only tested the few functions I needed to use :)
