### ISSUE TITLE
Implement get_sample_rate

### ISSUE THREAD

**Issue by wcampbell0x2a** [ppannuto/python-saleae#53]
https://github.com/ppannuto/python-saleae/blob/f005d9acbd903b4e9720a287f131c7da546e8f5e/saleae/saleae.py#L424

This is no longer true, per the document from Saleae: https://github.com/saleae/SaleaeSocketApi/blob/master/Doc/Logic%20Socket%20API%20Users%20Guide.md#get-selected-collection-sample-rate

**Comment by ppannuto** [comment]
Neat! Happy to take a PR that adds the new interface -- thanks!

**Comment by sophiekovalevsky** [comment]
@ppannuto first thing first, what a great tool that you have built :D thanks so much for all the great effort. 

In  a few seconds I will create a PR that aims to fix this issue.
