### ISSUE TITLE
enum34 should not be required above Python 3.4

### ISSUE THREAD

**Issue by iwane-pl** [ppannuto/python-saleae#57]
As Python 3.4 introduced enum module to the standard library, the requirement to install enum34 should be conditional to Python 2.7.

Current situation (unconditional requirement) breaks other modules depending on Enum (e.g. installing PyInstaller on Python 3.6 after installation of Saleae fails with ``'enum' module has no 'IntFlag'`` due to enum34 being imported before standard enum)

Environment: Python 3.6.8, Windows 10

**Comment by ppannuto** [comment]
Interesting -- that makes sense. I'm not great at the internals of python packaging, so if you can put together a PR that implements this, that would be amazing, otherwise I'll try to get to it in the next few weeks.

**Comment by iwane-pl** [comment]
I'd love to, but I don't have a Saleae Logic available at home and cannot do it at work (IP rights claim from the employer) - the PR would be untested then :(
Here's some information on this: https://hynek.me/articles/conditional-python-dependencies/ 

I'll still have the PR on mind if I manage to get my hands on Saleae setup at home.
