### ISSUE TITLE
Export data to a python container

### ISSUE THREAD

**Issue by tamenol** [ppannuto/python-saleae#73]
Is there a way to export the captured data to a numpy array or pandas datafram for immediate processing?

**Comment by ppannuto** [comment]
Not that I know of. I think natively creating such datatypes in this library would require adding dependencies on numpy or pandas, which isn't really appropriate for more general users. I think that conversion is something that will have to be done by the driving script generally.

If there is some reformatting / reframing (i.e. some `map` + `zip` combination or some such) that would be useful to prepare for export, I think adding a function like that would be appropriate, and I'm happy to consider a PR. It would just have to be build on native Python constructs.

**Comment by tamenol** [comment]
Ok, understandable. Might have a jab at it once I've got some more time but no promises.
