### ISSUE TITLE
Getting a type error while executing the launch_logic method

### ISSUE THREAD

**Issue by raj1234556** [ppannuto/python-saleae#81]
While executing the launch logic method, I am getting a type error, but the application is opening.

![image](https://user-images.githubusercontent.com/91521326/167546480-b6869be1-0bdd-40f5-ad53-9c063578f478.png)

**Comment by ppannuto** [comment]
You must be passing an illegal value for `host` or `port` [probably host given that error], by default the arguments are not `None`:
> 	def launch_logic(timeout=15, quiet=False, host='localhost', port=10429, logic_path=None, args=None):

I think this is an error with your code, not this library; however if there is an issue with the library, please feel free to provide more details, as well as what might be a potential fix, and re-open this issue.
